#!/bin/bash
#
# /etc/init.d/jenkins-slave
#

Name="Jenkins Slave"
InstanceName="Docker_Server"
JenkinsUrl="http://192.168.50.102:8080/"
jerLocation="/home/tzahi"
Log="/var/log/jenkins"
Pidfile="/var/run/jenkins-slave.pid"
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

case "$1" in
   start)
      "$JAVA_HOME/bin/java" -jar $jerLocation/agent.jar -jnlpUrl $JenkinsUrl/computer/$InstanceName/slave-agent.jnlp -secret 1aa21cce9b3f00d4b2a0fa6e1b10863c95ea1a73a56b7a70b065560dcae3854e -workDir "/var/jenkins"
      Pid=$!
      if [ -z $Pid ]; then
         printf "%s\n" "Fail"
      else
         echo $Pid > $Pidfile
         printf "%s\n" "Ok"
      fi
      ;;

   stop)
      printf "%-50s" "Stopping $Name"
      Pid=`cat $Pidfile`
      if [ -f $Pidfile ]; then
         kill -TERM $Pid
         printf "%s\n" "Ok"
         rm -f $Pidfile
      else
         printf "%s\n" "pidfile not found"
      fi
      ;;

   restart)
      $0 stop
      $0 start
      ;;

   status)
      printf "%-50s" "Checking $Name..."
      if [ -f $Pidfile ]; then
         Pid=`cat $Pidfile`
         if [ -z "`ps axf | grep ${Pid} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
            echo "Pidfile: $Pidfile"
         else
            echo "Running"
            echo "Pid: $Pid"
            echo "Pidfile: $Pidfile"
         fi
      else
         printf "%s\n" "Service not running"
      fi
      ;;

   *)
      echo "Usage: $0 {start|stop|restart}"
      ;;
esac