---
- name: Adding Public SSH Certificate For User
  hosts: all
  tasks:

  - name: Make .ssh Direcotry
    file:
      path: "/home/tzahi/.ssh"
      state: directory

  - name: Create Empty authorized_keys File
    file:
      path: "/home/tzahi/.ssh/authorized_keys"
      state: touch

  - name: Copy Certificate File From Local Server with owner and permissions
    copy:
      src: /tmp/id_ed25519.pub
      dest: /home/tzahi/.ssh/
      owner: tzahi
      group: tzahi
      mode: '0600'


