---
- name: PlayBook To Install Ansible
  hosts: all
  tasks:

  - name: Installing Ansible Package
    apt:
      name: ansible
      state: present
      update_cache: yes
      
  - name: install community.general docker plgin for ansible
    shell: ansible-galaxy collection install community.general
