---
- name: Installing Puppet Agent Service Playbook
  hosts: all
  become: true
  tasks:

  - name: Install puppet .deb package from the internet
    apt:
      deb: https://apt.puppetlabs.com/puppet7-release-focal.deb
    
  - pause: seconds=10
    
  - name: Update all Packages to Their Latest Version
    apt:
      name: "*"
      state: latest

  - pause: seconds=10

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist
    
  - pause: seconds=10
    
  - name: Update apt and Install puppet-agent
    apt: 
      update_cache: yes 
      name: puppet-agent
      state: latest

  - name: Create File puppet.conf
    file:
      path: /etc/puppetlabs/puppet/puppet.conf
      state: touch

  - name: Update hosts File
    lineinfile:
      path: /etc/hosts
      state: present
      line: '192.168.50.96 puppet puppet.localdomain'
  
  - name: Update hosts File
    lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ item }}"
    with_items:
    - '192.168.50.96 puppet puppet.localdomain'
    - '192.168.50.73 ops03 ops03.localdomain'
     
  - name: Update puppet.conf File
    lineinfile:
      path: /etc/puppetlabs/puppet/puppet.conf
      state: present
      line: "{{ item }}"
    with_items:
    - '[main]'
    - 'certname = ops03'
    - 'server = puppet'
    
  - name: Starting The puppet Agent Service
    systemd:
      name: puppet
      state: started
      enabled: yes

  - name: Execute a command to Register Puppet Service
    become: true
    shell: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
    
